<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PT1238LXLT" name="Plivo Message Test" tests="6" failures="1" timestamp="8 Aug 2018 10:16:42 GMT" time="14.771" errors="0">
  <testcase name="getNumbers" time="5.445" classname="com.plivo.tests.MessageTest"/>
  <testcase name="sendMessage" time="2.19" classname="com.plivo.tests.MessageTest"/>
  <testcase name="readMsgCharge" time="2.296" classname="com.plivo.tests.MessageTest"/>
  <testcase name="getOutboundRate" time="2.731" classname="com.plivo.tests.MessageTest"/>
  <testcase name="verifyCashCredit" time="2.071" classname="com.plivo.tests.MessageTest">
    <failure type="java.lang.AssertionError" message="Unexpectedly cashCredits is greater than msgCharge as cashCredits: 11.20779 and msgCharge: 0.0035 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Unexpectedly cashCredits is greater than msgCharge as cashCredits: 11.20779 and msgCharge: 0.0035 expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.plivo.tests.MessageTest.verifyCashCredit(MessageTest.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyCashCredit -->
  <testcase name="verifyMsgAmount" time="0.002" classname="com.plivo.tests.MessageTest"/>
</testsuite> <!-- Plivo Message Test -->
